namespace RagNet.Abstractions;

/// <summary>
/// Complete result of a RAG pipeline execution.
/// Includes the generated response and citations for the sources used.
/// </summary>
public record RagResponse
{
    /// <summary>Text of the response generated by the LLM.</summary>
    public required string Answer { get; init; }

    /// <summary>Citations/references to the source documents used.</summary>
    public IReadOnlyList<Citation> Citations { get; init; } = Array.Empty<Citation>();

    /// <summary>Execution metadata of the pipeline (times, tokens, etc.).</summary>
    public Dictionary<string, object> ExecutionMetadata { get; init; } = new();
}
